extends EventData
class_name HitReportData #stores information about a hit's effect; is generated by the target of a hit

var target: Unit
var damage_caused: float = 0.0
var death_caused: bool = false
