extends EventData
class_name HitReportData #stores information about a hit's effect; is generated by the target of a hit

#hit information/effects
var source: Unit ##source of the hit's damage
var target: Unit ##eventual target of the hit
var damage_caused: float = 0.0 ##how much damage did the target receive
var death_caused: bool = false ##did the target die?
#potential death effects
var flux_value: float = 0.0 ##if target killed by hit, how much flux does it drop?
