class_name Relics
#NOTE: this phrasing "static var" instead of "const ... preload()" is needed due to strange parser error bugs
static var MONEY_MARKET: RelicData = load("res://Content/Relics/money_market/money_market.tres")
static var SUBPRIME: RelicData = load("res://Content/Relics/subprime/subprime.tres")
static var STUMBLING_BLOCKS: RelicData = load("res://Content/Relics/stumbling_blocks/stumbling_blocks.tres")
static var COMMON_COLD: RelicData = load("res://Content/Relics/common_cold/common_cold.tres")
static var CONTAGION: RelicData = load("res://Content/Relics/contagion/contagion.tres")
static var WILDERNESS: RelicData = load("res://Content/Relics/wilderness/wilderness.tres")
static var TRANCE: RelicData = load("res://Content/Relics/trance/trance.tres")
static var ENFILADE: RelicData = load("res://Content/Relics/enfilade/enfilade.tres")
static var AMBUSH: RelicData = load("res://Content/Relics/ambush/ambush.tres")
static var INFERNO: RelicData = load("res://Content/Relics/inferno/inferno.tres")
static var DYNAMITE: RelicData = load("res://Content/Relics/dynamite/dynamite.tres")
static var MUCOUS_SAC: RelicData = load("res://Content/Relics/mucous_sac/mucous_sac.tres")
static var AMETHYST_SKULL: RelicData = load("res://Content/Relics/amethyst_skull/amethyst_skull.tres")
static var ICE_SHARDS: RelicData = load("res://Content/Relics/ice_shards/ice_shards.tres")
static var WHITE_HOT_IRON: RelicData = load("res://Content/Relics/white_hot_iron/white_hot_iron.tres")
static var EARLY_BIRD: RelicData = load("res://Content/Relics/early_bird/early_bird.tres")
static var MACUAHUITL: RelicData = load("res://Content/Relics/macuahuitl/macuahuitl.tres")
static var MOKA_POT: RelicData = load("res://Content/Relics/moka_pot/moka_pot.tres")
static var PAPER_UMBRELLA: RelicData = load("res://Content/Relics/paper_umbrella/paper_umbrella.tres")
static var PAWN_STRUCTURE: RelicData = load("res://Content/Relics/pawn_structure/pawn_structure.tres")
static var SIGNAL_FLAG: RelicData = load("res://Content/Relics/signal_flag/signal_flag.tres")

static var relics: Dictionary[RelicData.Type, RelicData] = {} ## relics indexed by type, loaded by reward_service
